# Loading Data & Visualization

In [21]:
# Import the needed libraries 
import pandas as pd 
import yfinance as yf

In [22]:
# import raw data from yfinance
raw = yf.download('^GSPC', start='2000-01-01')

[*********************100%***********************]  1 of 1 completed

In [23]:
# check our loaded data 
raw

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2000-01-03  1455.219971  1478.000000  1438.359985  1469.250000   931800000
2000-01-04  1399.420044  1455.219971  1397.430054  1455.219971  1009000000
2000-01-05  1402.109985  1413.270020  1377.680054  1399.420044  1085500000
2000-01-06  1403.449951  1411.900024  1392.099976  1402.109985  1092300000
2000-01-07  1441.469971  1441.469971  1400.729980  1403.449951  1225200000
...                 ...          ...          ...          ...         ...
2026-04-21  7064.009766  7137.270020  7050.200195  7122.640137  5160270000
2026-04-22  7137.899902  7138.640137  7102.910156  7102.910156  4919460000
2026-04-23  7108.399902  7147.779785  7046.549805  7118.799805  5307260000
2026-04-24  7165.080078  7168.589844  7112.819824  7136.479980  4608830000
2026-04-27  7159.540039  7167.700195  7148.419922  7152.720215   814889249

[6618 rows x 5 columns]

## OHLCV
### On a Given trading day: 
### 1- The Market Open at 9:30 AM, the first price to trade is the Open column.
### 2- The price change during the day trading, the Highest Price is the High column.
### 3- The Lowest price during a trading day is the Low column.
### 4- The Market typically close at 4:00 PM, The Close price is the Close column.
### 5- The Total number of shares traded in one day is the Volumne column

## Data Inspection

In [24]:
# Check the DataSet shape
raw.shape

(6618, 5)

In [25]:
type(raw.index)

pandas.DatetimeIndex

In [26]:
# Check for missing values 
raw.isnull().sum()

Price   Ticker
Close   ^GSPC     0
High    ^GSPC     0
Low     ^GSPC     0
Open    ^GSPC     0
Volume  ^GSPC     0
dtype: int64

In [27]:
# Check Data description 
raw.describe()

Price         Close         High          Low         Open        Volume
Ticker        ^GSPC        ^GSPC        ^GSPC        ^GSPC         ^GSPC
count   6618.000000  6618.000000  6618.000000  6618.000000  6.618000e+03
mean    2323.547094  2336.385554  2308.958188  2323.181012  3.443569e+09
std     1528.532531  1535.253947  1520.552931  1528.180115  1.525625e+09
min      676.530029   695.270020   666.789978   679.280029  0.000000e+00
25%     1213.412506  1220.117493  1205.320038  1213.010010  2.335715e+09
50%     1550.350037  1555.895020  1543.244995  1549.359985  3.543175e+09
75%     2929.767517  2940.292419  2915.535034  2926.235046  4.288205e+09
max     7165.080078  7168.589844  7148.419922  7152.720215  1.145623e+10

## The Minimum value of the volume is 0, which shouldn't be the case, we inspect that further

In [28]:
# Flatten multi-level columns
raw.columns = raw.columns.get_level_values(0)
raw.head()

Price             Close         High          Low         Open      Volume
Date
2000-01-03  1455.219971  1478.000000  1438.359985  1469.250000   931800000
2000-01-04  1399.420044  1455.219971  1397.430054  1455.219971  1009000000
2000-01-05  1402.109985  1413.270020  1377.680054  1399.420044  1085500000
2000-01-06  1403.449951  1411.900024  1392.099976  1402.109985  1092300000
2000-01-07  1441.469971  1441.469971  1400.729980  1403.449951  1225200000

In [29]:
# How many days have a volume of 0
raw[raw['Volume'] == 0]

Price             Close         High         Low         Open  Volume
Date
2023-05-24  4115.240234  4132.959961  4103.97998  4132.959961       0

### The day 24th of May 2023 is a normal tradin day, it might be something wrong on yfinance data, 
### We drop the row for that day

### When inspecting the Volume for last day it was relatively low, the reason I found is the trading day has NOT finished yet
### or yfinance didn't didn't update the last trading day
### for forecasting purposes, an incomplete trading day can skew my most recent data point.

In [31]:
# We drop the rows that has Zero volume by 
raw = raw[raw['Volume']  > 0]