# Loading Data & Visualization

In [7]:
# Import the needed libraries 
import pandas as pd 
import yfinance as yf

In [8]:
# import raw data from yfinance
raw = yf.download('^GSPC', start='2000-01-01')

[*********************100%***********************]  1 of 1 completed

In [10]:
# check our loaded data 
raw

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2000-01-03  1455.219971  1478.000000  1438.359985  1469.250000   931800000
2000-01-04  1399.420044  1455.219971  1397.430054  1455.219971  1009000000
2000-01-05  1402.109985  1413.270020  1377.680054  1399.420044  1085500000
2000-01-06  1403.449951  1411.900024  1392.099976  1402.109985  1092300000
2000-01-07  1441.469971  1441.469971  1400.729980  1403.449951  1225200000
...                 ...          ...          ...          ...         ...
2026-04-15  7022.950195  7026.240234  6967.129883  6978.169922  5278610000
2026-04-16  7041.279785  7051.229980  7008.520020  7037.779785  5173650000
2026-04-17  7126.060059  7147.520020  7074.549805  7074.549805  6145300000
2026-04-20  7109.140137  7122.649902  7084.410156  7117.049805  4661130000
2026-04-21  7100.020020  7137.270020  7062.089844  7122.640137  1983339000

[6614 rows x 5 columns]

### The columns is for SP500 ticker for Close, High, Low and Open Prices resprectively and the Volume for each date

In [11]:
# Check the DataSet shape
raw.shape

(6614, 5)

In [12]:
type(raw.index)

pandas.DatetimeIndex

In [ ]:
# Check for missing values 
raw.isnull().sum()

Price   Ticker
Close   ^GSPC     0
High    ^GSPC     0
Low     ^GSPC     0
Open    ^GSPC     0
Volume  ^GSPC     0
dtype: int64

In [13]:
# Check Data description 
raw.describe()

Price         Close         High          Low         Open        Volume
Ticker        ^GSPC        ^GSPC        ^GSPC        ^GSPC         ^GSPC
count   6614.000000  6614.000000  6614.000000  6614.000000  6.614000e+03
mean    2320.638004  2333.470954  2306.060853  2320.275330  3.442805e+09
std     1524.408141  1531.134655  1516.439205  1524.065543  1.525356e+09
min      676.530029   695.270020   666.789978   679.280029  0.000000e+00
25%     1213.302521  1220.070038  1205.152496  1212.684967  2.334325e+09
50%     1549.375000  1555.259949  1541.135010  1548.075012  3.543045e+09
75%     2926.459961  2939.020081  2913.644958  2924.752502  4.286500e+09
max     7126.060059  7147.520020  7084.410156  7122.640137  1.145623e+10

## The Minimum value of the volume is 0, which shouldn't be the case, we inspect that further

In [ ]:
# How many days have a volume of 0
raw[raw[('Volume', '^GSPC')] == 0]

Price             Close         High         Low         Open Volume
Ticker            ^GSPC        ^GSPC       ^GSPC        ^GSPC  ^GSPC
Date
2023-05-24  4115.240234  4132.959961  4103.97998  4132.959961      0

In [ ]:
# We drop the missing row date for the day with Volume of 0
raw = raw.drop(raw[raw[('Volume', '^GSPC')] == 0])

KeyError: ('Volume', '^GSPC')

In [16]:
# Flatten multi-level columns
raw.columns = raw.columns.get_level_values(0)
raw.head()

Price             Close         High          Low         Open      Volume
Date
2000-01-03  1455.219971  1478.000000  1438.359985  1469.250000   931800000
2000-01-04  1399.420044  1455.219971  1397.430054  1455.219971  1009000000
2000-01-05  1402.109985  1413.270020  1377.680054  1399.420044  1085500000
2000-01-06  1403.449951  1411.900024  1392.099976  1402.109985  1092300000
2000-01-07  1441.469971  1441.469971  1400.729980  1403.449951  1225200000